name: Hello World Workflow

on:
  push:
    branches:
      - main  # This triggers the workflow when changes are pushed to the 'main' branch.

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the runner environment.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository.

      - name: Read hello.txt and print its content
        run: |
          cat hello.txt  # Reads and outputs the content of hello.txt to the log.
