name : Print Txt File

on:
  push:
    branches:
      -main
  pull request:
    branches:
      -main

jobs:
  read_the_file:
  runs-on:ubuntu-latest
  steps:
    - name: Git Checkout korte hobe
      uses: actions/checkout@v2
    - name: Read the Txt File
      run :
        ls -l
        cat hello.txt